# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# This file contains a template configuration file, which is typically
# placed as .hlint.yaml in the root of your project


# Specify additional command line arguments
#
# - arguments: [--color, --cpp-simple, -XQuasiQuotes]


# Control which extensions/flags/modules/functions can be used
#
# - extensions:
#   - default: false # all extension are banned by default
#   - name: [PatternGuards, ViewPatterns] # only these listed extensions can be used
#   - {name: CPP, within: CrossPlatform} # CPP can only be used in a given module
#
# - flags:
#   - {name: -w, within: []} # -w is allowed nowhere
#
# - modules:
#   - {name: [Data.Set, Data.HashSet], as: Set} # if you import Data.Set qualified, it must be as 'Set'
#   - {name: Control.Arrow, within: []} # Certain modules are banned entirely
#
# - functions:
#   - {name: unsafePerformIO, within: []} # unsafePerformIO can only appear in no modules


# Add custom hints for this project
#
# Will suggest replacing "wibbleMany [myvar]" with "wibbleOne myvar"
# - error: {lhs: "wibbleMany [x]", rhs: wibbleOne x}


# Turn on hints that are off by default
#
# Ban "module X(module X) where", to require a real export list
# - warn: {name: Use explicit module export list}
#
# Replace a $ b $ c with a . b $ c
# - group: {name: dollar, enabled: true}
#
# Generalise map to fmap, ++ to <>
- group: {name: generalise, enabled: true}
- group: {name: generalise-for-conciseness, enabled: true}
- group: {name: monomorphic, enabled: true}


# Ignore some builtin hints
- ignore: {name: Use infix}
- ignore: {name: Use fmap}
- ignore: {name: Use section}
# - ignore: {name: Use const, within: SpecialModule} # Only within certain modules


# Define some custom infix operators
# - fixity: infixr 3 ~^#^~

- arguments: [-XDataKinds -XDefaultSignatures -XDeriveAnyClass -XDeriveGeneric -XDerivingStrategies -XDerivingVia -XDuplicateRecordFields -XFlexibleContexts -XGADTs -XGeneralizedNewtypeDeriving -XKindSignatures -XLambdaCase -XOverloadedLists -XOverloadedStrings -XRankNTypes -XRecordWildCards -XScopedTypeVariables -XTypeApplications -XTypeFamilies -XTypeOperators]

# To generate a suitable file for HLint do:
# $ hlint --default > .hlint.yaml
# This is a custom hlint config with rules that suggest
# using Universum functions whenever it has a suitable
# alternative. You may either copy-paste this config into
# your .hlint.yaml or run hlint twice: once with your
# default config, and the second time with this one.
# This config is *not* intended for Universum developers.

